### ISSUE TITLE
Creates a gibberish file.

### ISSUE THREAD

**Issue by ghost** [DhavalKapil/image-uploader#3]
I am running PHP 7 (might be relevant) and have been trying to use your image-uploader. 

I follow your directions completely, I mean it's all very simple to use. It seems to work perfectly fine... until you go look at the file uploaded. Which ends up being a file with no extension name and full of gibberish. Renaming to a proper file format or opening it in an image program just throws an error that the file might be corrupted.

I have no idea what I am doing because the steps are super simple, I even test uploading invalid images or file types and it throws errors perfectly. It's all working... minus the resulting file being correct!

**Comment by DhavalKapil** [comment]
Hi! I'm glad you found it easy to use :)

The uploaded image file is stored with no extension by implementation.
I didn't quite understand the issue. Is the image file gibberish when it is served or is it just gibberish when it is stored? Is this happening with multiple uploaded files or just 1?

Also it would be helpful if you could provide some source code as to how you are using. You can also mail me the uploaded file and the gibberish file at me@dhavalkapil.com. I'll have a look.

**Comment by ghost** [comment]
Sent you an email. I think the issue was that I didn't realize you had to use the serve function. I just wanted secure image upload, is there anyway to modify the script to upload image in a format I want? I don't want to use the serve function.

thanks!
